name: 'Scan github action'
description: 'A github action to scan repositories Dockerfile'
inputs:
  GH_TOKEN:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4 
      name: Setting python version
      with:
        python-version: 'pypy3.9'
        
    - run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
      name: Installing dependencies
      
    - run: | 
        export GH_TOKEN=${{ inputs.GH_TOKEN }}
        python $GITHUB_ACTION_PATH/src/main.py --
      shell: bash
      name: Executing action
